# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='Time')),
                ('buyer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('size', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=50)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ask', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
