# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trade_time',
            field=models.IntegerField(default=0),
        ),
    ]
