# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20170301_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_time',
            field=models.DateTimeField(),
        ),
    ]
