# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_trade_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buyer',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller',
            field=models.EmailField(max_length=254),
        ),
    ]
