# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20170302_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly', models.CharField(max_length=50)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Trade')),
            ],
        ),
    ]
