# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alert_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(default='Fat finger', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
