# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20170304_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='price_intercept',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='price_slope',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
