# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_auto_20170304_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='price_intercept',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='market',
            name='price_slope',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
    ]
