# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20170306_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='anomalous_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='market',
            name='fluctuation',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='market',
            name='pd_track_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='market',
            name='sda_price_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
