# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_delete_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='category',
        ),
        migrations.AddField(
            model_name='alert',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Market'),
        ),
    ]
