# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_auto_20170309_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='sector',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
