# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_market_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
    ]
