# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('day_size_avg', models.IntegerField(default=0)),
                ('current_day_size', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
            ],
        ),
    ]
