# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='false_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
