# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_auto_20170309_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='occur_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
