# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_auto_20170309_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='sector',
            field=models.CharField(max_length=50),
        ),
    ]
